### ISSUE TITLE
yInsure/yCover docs out of date

### ISSUE THREAD

**Issue by lex-node** [iearn-finance/docs#73]
Recently the community discussed that "insurance" is inaccurate for describing "coverage" through Nexus Mutual and also has adverse regulatory implications. 

The terminology has been changed from "insurance" to "cover" in some places on yearn.finance, but [yInsure docs](https://docs.yearn.finance/products/yinsure) should be further updated to make the terminology change consistent. 

Also suggest adding a link on the same page to Nexus Mutual materials (or other materials, if Nexus Mutual has not published them) explaining the difference between coverage and insurance.

**Comment by wirjo** [comment]
Happy to assist with this. We can refer to the [Understanding Nexus Mutual medium post](https://medium.com/nexus-mutual/understanding-nexus-mutual-bb2946dad919):

> **Not insurance**
> Nexus Mutual does not offer insurance because it is a discretionary mutual. Smart Contract Cover is not a contract of insurance. It is discretionary cover provided by members of the mutual to each other. Members have full discretion on which claims payments are made. Members are putting trust in the economic incentive model rather than an insurance company.
